export const FETCH_NOTIFICATION_HISTORY_REQUEST = 'FETCH_NOTIFICATION_HISTORY_REQUEST';
export const FETCH_NOTIFICATION_HISTORY_SUCCESS = 'FETCH_NOTIFICATION_HISTORY_SUCCESS';
export const FETCH_NOTIFICATION_HISTORY_FAILURE = 'FETCH_NOTIFICATION_HISTORY_FAILURE';

export const SEND_NOTIFICATION_REQUEST = 'SEND_NOTIFICATION_REQUEST';
export const SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS';
export const SEND_NOTIFICATION_FAILURE = 'SEND_NOTIFICATION_FAILURE';